### PR TITLE
Submit project for review

### PR DESCRIPTION
**Pull request by kimfom01**
In this project, I am fetching movie details from an external api to populate my database then I can display it in the app, so there is no update method on the database, only reads, bulk writes and bulk deletes
If there are no movies you can navigate to the admin page and fetch movies with a filter (by minimum rating) then go back to the main page.

### CODE REVIEW

**Comment by TheCSharpAcademy** [comment]
@kimfom01 Just double checking you're not getting this error?  It happens when I try to fetch movies

image

**Comment by kimfom01** [comment]
> 

maybe clear cache and try again? I am not getting any errors on my side

**Comment by kimfom01** [comment]
I deleted the db, applied migrations and launched the project still worked.

**Comment by kimfom01** [comment]
I have added a readme along with a gif showing the site and its "feature" :sweat_smile: 
I also made some changes like adding a background image, fixing the ui for the footer, changing the colors of the text to match the new background, justifying the filter form in the admin page to center

**Pull request merged**
